module.exports = {
   forcedDependencies: {
      dependencies: {
         "@lumx/core": "^3.6.7",
         "@lumx/icons": "^3.6.7",
         "@lumx/react": "^3.6.7",
         "lumapps-sdk-js": "1.37.0",
         react: "17.0.2",
         "react-dom": "17.0.2",
      },
      devDependencies: {
         "@lumapps-extensions-playground/devenv": "1.27.0",
         "@lumapps-extensions/shipping-server": "1.9.3-rc.1",
         "@types/react": "17.0.2",
         "@types/react-dom": "17.0.2",
      },
   },
   optionalDependencies: {
      axios: "0.27.2",
      lodash: "4.17.21",
      moment: "^2.30.1",
      "moment-range": "^4.0.2",
      "react-intl": "5.24.0",
      "react-redux": "7.2.6",
      reselect: "^4.1.5",
      "@testing-library/jest-dom": "^6.4.2",
      "@testing-library/react": "^14.2.2",
      "@testing-library/user-event": "^14.5.2",
      "@types/jest": "^29.5.12",
      "@types/lodash": "^4.17.0",
      "@types/node": "^20.12.2",
      "@types/react-redux": "^7.1.33",
      "@typescript-eslint/eslint-plugin": "^7.5.0",
      "@typescript-eslint/parser": "^7.5.0",
      eslint: "^8.57.0",
      "eslint-config-airbnb": "^19.0.4",
      "eslint-config-prettier": "^9.1.0",
      "eslint-plugin-import": "^2.29.1",
      "eslint-plugin-jsx-a11y": "^6.8.0",
      "eslint-plugin-prettier": "^5.1.3",
      "eslint-plugin-react": "^7.34.1",
      "eslint-plugin-react-hooks": "^4.6.0",
      jest: "^29.7.0",
      "npm-run-all": "^4.1.5",
      prettier: "3.2.5",
      "prettier-stylelint": "^0.4.2",
      "react-scripts": "^5.0.1",
      stylelint: "^16.3.1",
      "stylelint-config-idiomatic-order": "^10.0.0",
      "stylelint-config-recommended": "^14.0.0",
      "stylelint-config-recommended-scss": "^14.0.0",
      "stylelint-scss": "^6.2.1",
      "ts-loader": "9.5.1",
      typescript: "^5.4.3",
   },
};
